export const DUMMY_USERS = [
  {
    id: 1,
    nama: "John Doe",
    email: "john@example.com",
    nim: "2021001",
    jurusan: "ti",
    role: "mahasiswa",
    status: "active",
    terakhirLogin: "2025-01-18",
  },
  {
    id: 2,
    nama: "Jane Smith",
    email: "jane@example.com",
    nim: "2021002",
    jurusan: "si",
    role: "mahasiswa",
    status: "active",
    terakhirLogin: "2025-01-17",
  },
  {
    id: 3,
    nama: "Bob Johnson",
    email: "bob@example.com",
    nim: "2021003",
    jurusan: "ti",
    role: "admin",
    status: "inactive",
    terakhirLogin: "2025-01-05",
  },
  {
    id: 4,
    nama: "Alice Brown",
    email: "alice@example.com",
    nim: "2021004",
    jurusan: "bd",
    role: "mahasiswa",
    status: "suspended",
    terakhirLogin: "2024-12-20",
  },
];

export const DUMMY_COURSES = [
  {
    id: 1,
    user_id: 2,
    nama_matkul: "Pemograman Web",
    nama_dosen: "Jane Doe",
    hari: "senin",
    jam_mulai: "08:00",
    jam_selesai: "10:00",
    ruangan: "A101",
  },
  {
    id: 2,
    user_id: 3,
    nama_matkul: "Pemograman Web 2",
    nama_dosen: "John Doe",
    hari: "selasa",
    jam_mulai: "11:00",
    jam_selesai: "13:00",
    ruangan: "A102",
  },
  {
    id: 3,
    user_id: 2,
    nama_matkul: "DDP",
    nama_dosen: "Anonim",
    hari: "kamis",
    jam_mulai: "08:00",
    jam_selesai: "10:00",
    ruangan: "A104",
  },
];

export const DUMMY_TASKS = [
  {
    id: 1,
    user_id: 2,
    course_id: 1,
    nama_tugas: "Tugas 1",
    deskripsi: "lorem ipsum dolor",
    deadline: "2026-01-25",
    prioritas: "medium",
    is_done: true,
  },
  {
    id: 2,
    user_id: 2,
    course_id: 2,
    nama_tugas: "Tugas 2",
    deskripsi: "lorem ipsum dolor",
    deadline: "2026-01-28",
    prioritas: "low",
    is_done: false,
  },
  {
    id: 3,
    user_id: 3,
    course_id: 3,
    nama_tugas: "Tugas 10",
    deskripsi: "lorem ipsum dolor",
    deadline: "2026-01-28",
    prioritas: "high",
    is_done: true,
  },
];
